### ISSUE TITLE
Provide Application Page Status View API

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-application#30]
# Feature Request

## Description
Similarly to how we provide the application overlay and overlay provider we should offer an application page status view and application page status view provider.

I imagine this status view should overlay content instead of be rendered amongst it. We can also take this opportunity to limit the api.
One status view per provider.

## Additional Context / Screenshots
It could look something like this to consume.
```jsx
import React, { useState } from 'react';
import ApplicationPageStatus from 'terra-application/lib/application-page-status';
const ExampleComponent = () => {
  const [isError, setIsError] = useState(false);
  return (
    <div>
      <p>This component toggles an error state that lasts for 3 seconds.</p>
      <p>
        <button type="button" onClick={() => {
          setIsLoading(true);
          setTimeout(() => {
            setIsError(false);
          }, 3000);
        }}>
          Start Loading
        </button>
      </p>
      <ApplicationPageStatus type='Error' isOpen={isLoading} message='this page failed'/>
    </div>
  );
};
export default ExampleComponent;

```

**Comment by avinashg1994** [comment]
# Tech Design

## Summary
Create ApplicationPageStatusView API used to render terra-status-view within the application.

Implementation is similar to the [Application Loading Overlay](https://github.com/cerner/terra-application/tree/master/src/application-loading-overlay).

## I18N / Bidirectionality
Alignment will be mirrored in rtl orientation.

## Files

1. ApplicationPageStatusView.jsx
2. ApplicationPageStatusViewContext.jsx
3. ApplicationPageStatusViewProvider.jsx
4. ApplicationPageStatusViewProvider.module.scss

## React Props:

### ApplicationPageStatusView

| Props					| Type          |isRequired 	| Default  		| Description                                                                                           |
| ------------- 		        |:-------------:|:-------------:| --------		|------------                                                                                           |
| **buttonAttrs**      	                | arrayOf{ "name": "shape", "value": "Button.propTypes", "computed": true } 		|   optional    | **[]**	        |An array of objects containing terra-button properties. A key attribute is required for each object. This array is used to render buttons in the bottom section. Example:[{ text: 'Button 1', key: 1, size: 'medium', variant: 'action', onClick: onClickFunction}]                
| **message**      	                | string 		|   optional    | **undefined**	        |The descriptive text, displayed under the title                                                                      |
| **title** 		        | string      	|   optional 	| **undefined**	        |The title displayed under the glyph. Variants contain default titles that can be overriden by this prop                                                                   |
| **variant**      	        | enum 		|   optional    | **undefined**	        |Sets the glyph and title using a pre-baked variant. One of the following: no-data, no-matching-results, not-authorized, or error                                                               |
| **isOpen**      	        | bool 		|   optional    | **undefined**	        |A boolean value indicating whether the status view should be visible or not.                                                   |

#### Note:
The following terra-status-view props will not be exposed:
1. customGlyph
2. isAlignedTop
3. isGlyphHidden

### ApplicationPageStatusViewProvider

| Props					| Type                  |isRequired 	| Default  		| Description                                                                                           |
| ------------- 		        |:---------------------:|:-------------:| --------		|------------                                                                                           |
| **children**      	                | node          	|   optional 	| **none**		|The components to be rendered within the context of the ApplicationPageStatusViewProvider. Components rendered here are able to interact with ApplicationPageStatusViewProvider through the ApplicationPageStatusViewContext.                                                                        |
| **scrollRefCallback**      	                | func        	|   optional    | **none**	        |A function to be called with the current ref of the scrollable element rendered within the ApplicationPageStatusViewProvider.                                                                        |

## Example:
### ApplicationPageStatusView
```jsx
<ApplicationPageStatusView 
  variant='error'
  isOpen=true
  message='This page failed due to an error'
/>
```

### ApplicationPageStatusViewProvider
```jsx
<ApplicationPageStatusViewProvider>
  <ApplicationPageStatusView variant='error' isOpen={showErrorStatusView} />
  <ApplicationPageStatusView variant='no-data' isOpen={showNoDataStatusView} />
</ApplicationPageStatusViewProvider>
```

## Edits:

**04/06/2020**

- Added 'buttonAttrs' to the exposed props list
- Removed 'isOpen' prop.

cc: @mjhenkes, @ryanthemanuel, @ShettyAkarsh

**Comment by nickpith** [comment]
Why the `isOpen` prop? 

I personally think that is overboard when you can just conditionally render. By the way, I'm also not a fan of `isOpen` on a modal or overlay either. In my opinion, it is not a very declarative approach in my mind because if I don't want something rendered I just won't render it. Also, by looking at https://github.com/cerner/terra-application/blob/master/src/application-loading-overlay/ApplicationLoadingOverlay.jsx#L29-L33, I wouldn't classify `isOpen` as optional because it won't render anything if not specified so `isOpen` is required to be `true` in order to show an overlay. Again this gets back to my dislike of `isOpen` because it seems to make things much more complex than it really needs to be.

> The following terra-status-view props will not be exposed:
> * buttonAttrs

Why not expose this so that page status views can contain a Refresh button or other actions that could be used to potentially recover from an error state? I thought I recall UX having designs that allowed for that sort of actions.

**Comment by mjhenkes** [comment]
+1 on @nickpith comments about 'isOpen'.  Lets remove it.
I also agree about allowing button attributes. @neilpfeiffer At this point do we expect standard buttons of some kind or do we keep the api open for any type of button?

**Comment by neilpfeiffer** [comment]
> At this point do we expect standard buttons of some kind or do we keep the api open for any type of button?

Even though there are better/best choices for which buttons consumers can use, since any theme can theoretically create button styles that might be more or less appropriate, and since we previously had just an open node as the API, I don't see any critical reason to lock the API down now that couples future changes in button as a dependency to also needing an update to Status-View, or here in an Application Page implementation.

Let's keep the `buttonAttrs` as pure passthrough at this point if exposed here as well, with a recommendation to use the neutral/default button variant (and only use the neutral button in all tests or examples).

**Comment by neilpfeiffer** [comment]
One thing to note that I believe may be coming soon with an update to status-view, the `title` may no longer able to override the text from the default provided signal words for any of the standard variants. Since `customGlyph` is not exposed, we may want to check with @sethbroox if `title` should also be not be exposed, if the intent is to provide for only standard application states like error, etc. and it would be removed later anyway.

**Comment by mjhenkes** [comment]
1. Yes
2. Last rendered wins? I don't think thats a valid scenario, lets just make sure it doesn't crash.
